# This file was generated by GoReleaser. DO NOT EDIT.
cask "jury" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "af4bf878eb6df4ef614546016e302b07d7daa3e32eb342d6d6569a2da93d5027"
      url "https://github.com/chaychoong/jury/releases/download/v#{version}/jury_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c1c0695e3311152b5e26b382209dc41e9fa0f32e21b5d2f41c7dc108a159d0f4"
      url "https://github.com/chaychoong/jury/releases/download/v#{version}/jury_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c5745e7df8e791c7b19e20b98836518a6b674502b7e1e38a5cb28180e524fbdc"
      url "https://github.com/chaychoong/jury/releases/download/v#{version}/jury_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3f0b8b8d33fec3ba6489d44dcd25f0e907eca86a8f134a9c5ae02340d86337eb"
      url "https://github.com/chaychoong/jury/releases/download/v#{version}/jury_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jury"
  desc "Multi-model adversarial review tool"
  homepage "https://github.com/chaychoong/jury"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jury"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status.zero?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jury"]
    end
  end

  # No zap stanza required

end
